### ISSUE TITLE
Error: the copy from .env.example to .env was not successful

### ISSUE THREAD

**Issue by abasslab** [softberg/quantum-php-core#50]
https://github.com/softberg/quantum-php-core/blob/c06e4f86192218274494a77c9be70bd02a1fd705/src/Console/Commands/EnvCommand.php#L49

The copy from .env.example to .env was not successful, but the success message is still displayed!

I got this error while creating a new project with the following command.
compose create-project quantum/project.

**Comment by armanist** [comment]
Thanks for following up, looks like the  copy('.env.example', '.env'); wasn't worked maybe because of permission issue?
Try to run `php qt core:env` command which will repeat the copy process, just to see it's happening again. 
Eventually you can du that process manually to be able to move forward.. The current development version which is v2.6 has much more changes and if I'm not wrong it also includes all the commands refactoring.

**Comment by abasslab** [comment]
> Thanks for following up, looks like the ` copy('.env.example', '.env');` wasn't worked maybe because of permission issue? Try to run `php qt core:env` command from terminal, which will repeat the copy process, just to see it's happening again. Eventually you can du that process manually to be able to move forward.. The current development version which is v2.6 has much more changes and if I'm not wrong it also includes all the commands refactoring.

The php qt core:env command works well

**Comment by armanist** [comment]
@abasslab on which operation system you have tried the project installation? 

For you information the project does the same `php qt core:env` command at installation.

**Comment by abasslab** [comment]
> 
I'm using Linux version 4.4.15+
